<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('tenants',function(Blueprint $t){$t->uuid('id')->primary();$t->string('name',150);$t->string('code',50)->unique();$t->string('sip_domain',190)->unique();$t->string('status',20)->index();$t->string('timezone',64);$t->string('default_language',10)->default('en');$t->unsignedInteger('extension_start');$t->unsignedInteger('extension_end');$t->unsignedInteger('max_extensions');$t->unsignedInteger('max_agents');$t->unsignedInteger('max_queues');$t->unsignedInteger('max_campaigns')->default(0);$t->unsignedInteger('max_concurrent_calls');$t->unsignedInteger('recording_retention_days')->default(90);$t->jsonb('features')->default('{}');$t->timestamps();$t->softDeletes();});
        Schema::create('users',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained()->cascadeOnUpdate()->restrictOnDelete();$t->string('name');$t->string('email')->unique();$t->timestamp('email_verified_at')->nullable();$t->string('password');$t->string('role',30)->index();$t->string('status',20)->default('ACTIVE')->index();$t->rememberToken();$t->timestamps();});
        Schema::create('password_reset_tokens',function(Blueprint $t){$t->string('email')->primary();$t->string('token');$t->timestamp('created_at')->nullable();});
        Schema::create('sessions',function(Blueprint $t){$t->string('id')->primary();$t->foreignUuid('user_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->longText('payload');$t->integer('last_activity')->index();});
        Schema::create('agents',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('user_id')->unique()->constrained()->cascadeOnDelete();$t->string('employee_code',50);$t->string('display_name');$t->string('status',20)->default('ACTIVE')->index();$t->timestamps();$t->unique(['tenant_id','employee_code']);});
        Schema::create('extensions',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('user_id')->nullable()->constrained()->nullOnDelete();$t->string('extension_number',16);$t->string('sip_username',100);$t->text('sip_password');$t->string('caller_id_name',100);$t->string('caller_id_number',32);$t->string('status',20)->default('ACTIVE')->index();$t->boolean('webrtc_enabled')->default(true);$t->boolean('voicemail_enabled')->default(false);$t->boolean('dnd_enabled')->default(false);$t->unsignedSmallInteger('ring_timeout')->default(30);$t->timestamps();$t->unique(['tenant_id','extension_number']);$t->unique(['tenant_id','sip_username']);});
        Schema::create('agent_sessions',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('agent_id')->constrained()->cascadeOnDelete();$t->foreignUuid('extension_id')->constrained()->restrictOnDelete();$t->string('work_mode',20);$t->string('status',30)->index();$t->uuid('current_call_id')->nullable()->index();$t->timestampTz('login_time');$t->timestampTz('logout_time')->nullable();$t->string('device_type',30);$t->string('ip_address',45)->nullable();$t->string('user_agent',500)->nullable();$t->timestamps();$t->index(['tenant_id','agent_id','logout_time']);});
        Schema::create('freeswitch_servers',function(Blueprint $t){$t->uuid('id')->primary();$t->string('name');$t->string('host');$t->unsignedSmallInteger('esl_port')->default(8021);$t->text('encrypted_esl_password');$t->string('status',20)->default('ACTIVE');$t->timestampTz('last_heartbeat_at')->nullable();$t->timestamps();});
        Schema::create('queues',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('number',20);$t->string('strategy',40)->default('longest-idle-agent');$t->unsignedInteger('wrap_up_seconds')->default(30);$t->unsignedInteger('max_wait_seconds')->default(300);$t->unsignedInteger('max_size')->default(100);$t->string('music_on_hold')->default('local_stream://moh');$t->string('status',20)->default('ACTIVE')->index();$t->timestamps();$t->unique(['tenant_id','number']);});
        Schema::create('queue_members',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('queue_id')->constrained('queues')->cascadeOnDelete();$t->foreignUuid('agent_id')->constrained()->cascadeOnDelete();$t->unsignedSmallInteger('priority')->default(1);$t->unsignedSmallInteger('skill')->default(1);$t->timestamps();$t->unique(['queue_id','agent_id']);});
        Schema::create('did_numbers',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->string('number',32)->unique();$t->string('destination_type',30);$t->uuid('destination_id');$t->string('status',20)->default('ACTIVE');$t->timestamps();$t->index(['tenant_id','status']);});
        Schema::create('ivr_flows',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('status',20)->default('DRAFT');$t->unsignedInteger('published_version')->nullable();$t->timestamps();});
        Schema::create('ivr_flow_versions',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('ivr_flow_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('version');$t->jsonb('definition');$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['ivr_flow_id','version']);});
        Schema::create('calls',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('agent_id')->nullable()->constrained()->nullOnDelete();$t->uuid('contact_id')->nullable()->index();$t->string('direction',20)->index();$t->string('type',30);$t->string('status',40)->index();$t->string('caller_id',32)->nullable();$t->string('destination_number',32);$t->timestampTz('started_at')->nullable()->index();$t->timestampTz('answered_at')->nullable();$t->timestampTz('bridged_at')->nullable();$t->timestampTz('ended_at')->nullable();$t->string('hangup_cause',100)->nullable();$t->uuid('disposition_id')->nullable();$t->text('notes')->nullable();$t->timestamps();$t->index(['tenant_id','created_at']);});
        Schema::create('call_legs',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('call_id')->constrained()->cascadeOnDelete();$t->uuid('leg_uuid')->unique();$t->string('leg_type',30);$t->string('direction',20);$t->string('endpoint');$t->string('status',40)->index();$t->timestampTz('answered_at')->nullable();$t->timestampTz('ended_at')->nullable();$t->string('hangup_cause',100)->nullable();$t->timestamps();});
        Schema::create('call_events',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('call_id')->constrained()->cascadeOnDelete();$t->string('idempotency_key')->unique();$t->string('event_type',80)->index();$t->string('status',40)->nullable();$t->jsonb('payload')->default('{}');$t->timestampTz('occurred_at')->index();$t->timestamps();});
        Schema::create('telephony_commands',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('call_id')->nullable()->constrained()->cascadeOnDelete();$t->string('type',40)->index();$t->string('status',20)->default('PENDING')->index();$t->jsonb('payload');$t->unsignedSmallInteger('attempts')->default(0);$t->text('error')->nullable();$t->timestampTz('processed_at')->nullable();$t->timestamps();});
        Schema::create('recordings',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();$t->foreignUuid('call_id')->constrained()->cascadeOnDelete();$t->string('storage_disk')->default('recordings');$t->string('storage_key');$t->string('mime_type',100)->default('audio/wav');$t->unsignedBigInteger('size_bytes')->nullable();$t->unsignedInteger('duration_seconds')->nullable();$t->timestampTz('expires_at')->nullable()->index();$t->timestamps();$t->unique(['tenant_id','storage_key']);});
        Schema::create('audit_logs',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('tenant_id')->nullable()->constrained()->nullOnDelete();$t->foreignUuid('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action',100)->index();$t->string('auditable_type')->nullable();$t->uuid('auditable_id')->nullable();$t->jsonb('before')->nullable();$t->jsonb('after')->nullable();$t->string('ip_address',45)->nullable();$t->string('user_agent',500)->nullable();$t->timestamps();$t->index(['tenant_id','created_at']);});
    }
    public function down(): void {foreach(['audit_logs','recordings','telephony_commands','call_events','call_legs','calls','ivr_flow_versions','ivr_flows','did_numbers','queue_members','queues','freeswitch_servers','agent_sessions','extensions','agents','sessions','password_reset_tokens','users','tenants'] as $table)Schema::dropIfExists($table);}
};
